### ISSUE TITLE
测试Java_LocalRmi的RemoteLoadApk出现报错Class is not registered: java.nio.HeapByteBuffer

### ISSUE THREAD

**Issue by thouger** [Thehepta/androidRPC#1]
源码没有修改，环境是安卓 10，将com/hepta/rmi/RmiClient.java 160 行的RemoteLoadApk函数打开注释，报错
`
Exception in thread "pool-1-thread-1" java.lang.IllegalArgumentException: Class is not registered: java.nio.HeapByteBuffer
Note: To register this class use: kryo.register(java.nio.HeapByteBuffer.class);
	at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:458)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:79)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:488)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:593)
	at com.esotericsoftware.kryonet.rmi.ObjectSpace$InvokeMethod.write(ObjectSpace.java:483)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.write(DefaultSerializers.java:427)
	at com.esotericsoftware.kryo.serializers.DefaultSerializers$KryoSerializableSerializer.write(DefaultSerializers.java:425)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:599)
	at com.esotericsoftware.kryonet.KryoSerialization.write(KryoSerialization.java:48)
	at com.esotericsoftware.kryonet.TcpConnection.send(TcpConnection.java:192)
	at com.esotericsoftware.kryonet.Connection.sendTCP(Connection.java:59)
	at com.esotericsoftware.kryonet.rmi.ObjectSpace$RemoteInvocationHandler.invoke(ObjectSpace.java:381)
	at jdk.proxy1/jdk.proxy1.$Proxy0.RemoteLoadApk(Unknown Source)
	at com.hepta.rmi.RmiClient.RemoteLoadApk(RmiClient.java:122)
	at com.hepta.rmi.RmiClient.onConnected(RmiClient.java:160)
	at com.hepta.rmi.RmiClient$1.connected(RmiClient.java:41)
`
感觉像是没有打开99 行的注释kryo.register(ByteBuffer.class);，打开了之后报错
`
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field final byte[] java.nio.ByteBuffer.hb accessible: module java.base does not "opens java.nio" to unnamed module @2b2948e2
`
之后就不知道怎么修复了，我看androidRPC 项目java/com/hepta/rmi/RmiServer.java的126 行同样是kryo.register(ByteBuffer.class);是可以使用的

**Comment by Thehepta** [comment]
这个框架我也没研究很多，有点记不太住了，你可以看看文档和demo,比较简单的
另外，这个RemoteLoadApk应该是没法用的，因为android 端动态加载内存的部分我已经完成，但是我记得好像是数据传输不过去，没法支持很大数据传输，目前我在用grpc框架

**Comment by thouger** [comment]
好吧，感谢回复
